### ISSUE TITLE
Unable to flash recovery to E3

### ISSUE THREAD

**Issue by LurnD** [99degree/LineageOS#1]
I have unlocked E3 after following your tutorial, but when I type `fastboot boot boot.img.clear`, it stucked at 'sending boot.img (24664 KB)`. I also tried to use Official TWRP Manager to flash boot.img, when I choose which image to flash, it launched File Explorer and can't select the image file. Then I click select file to flash button, it always crashed and cant open File Explorer.

**Comment by 99degree** [comment]
Please note the release is in alpha stage so it is not recommend to flash the boot.img into boot partition and I did not tried to do so too. and please remember the release works with some hw feature only. so you better to make a clear understanding about it.

if you can boot up with twrp then you can follow instruction to update vendor and system partition then boot with fastboot boot cmd. and then have a try with lineageos 17.1 first.

sometime's the img download is broken or adb is not working with the usb driver. so there are too many cause of problem. 

you can try with different boot img and see if it solve your problem.

also alpha 8 is available https://github.com/99degree/android_vendor_meizu_m851q/releases/tag/20200813

**Comment by 99degree** [comment]
BTW, boot.IMG are named as boot.IMG.xxxx either date or amber as suffix in resent release, its size about 12MB. Please have a check.

**Comment by LurnD** [comment]
Thanks for responding, I successfully flash the recovery image with TWRP Manager. Because I inserted an SD Card the Flyme can't choose which file to flash. But now I encountered another problem. Can you write a clear step of flashing LOS into E3. I flashed then it stuck at where the Logo lies? Or can you compile an complete ROM not the desperate img files?

**Comment by 99degree** [comment]
Sorry the device tree is not useful and i am not compiling the whole los myself. Thus the release is totally dependent to los Yandex Amber build. You can take a look my yt channel for the howto.

https://m.youtube.com/watch?v=P6zDCPg06Xc

**Comment by 99degree** [comment]
I believe you are a dev so you maybe interested to do some development on this phone. So here is the yt channel how i fix problem one by one up to now.

https://m.youtube.com/playlist?list=PLtLqIL6mAQaakA4nyvF3DecN7AedaQ_UA

**Comment by LurnD** [comment]
Sure I have followed your channel. I found this repo after checking youtube channel and your contents on xda fourm. But I still failed, after watching your video, this is weird.

**Comment by 99degree** [comment]
i supposed you had boot into android but stuck at los boot logo, the one eyed allen, then you can adb shell into the phone and see whats wrong. if adb is not available due to crypto issue, then you can modify build.prop to enforce. hope this helps

**Comment by LurnD** [comment]
Ok I will try it.

**Comment by costbusybox** [comment]
Now I have some ideas to make Los17.1Brush into Charm Blue E3, But I’m not sure if the steps are correct.

**Comment by costbusybox** [comment]
Turn off the phone, enter fastboot and connect to the computer
adb Brush in twrp v8000
Brush in system and vendor Partition
Reboot to fastboot
Brush in boot.img and recovery img.amber

**Comment by 99degree** [comment]
procedure is at xda. issue close.

https://forum.xda-developers.com/android/development/meizu-e3-lineageos-17-1-rom-porting-t4055605
